using DotEnv;
using DotEnv.SourceGenerator;

namespace Example.RandomDir;

[DotEnvAutoGenerated]
public static partial class AnotherEnvVars
{
    public static partial string StringVar { get; }
    public static partial float FloatVar { get; }
    public static partial long LongVar { get; }
    public static partial decimal DecimalVar { get; }
}