using DotEnv.SourceGenerator;

namespace Example;

[DotEnvAutoGenerated]
public static partial class EnvVars
{
    public static partial int IntVar { get; }
    public static partial double DoubleVar { get; }
    public static partial bool BoolVar { get; }
}

